export const fallbackProjects = [
  {
    id: 10,
    title: "SceneDiary",
    category: "Team Project",
    status: "In Progress",
    snapshot: "https://hqefyvwzlhytnmhqbggt.supabase.co/storage/v1/object/public/images/uploads/1781057615264_effa159c-48a0-4312-b635-52651a1d3741.png",
    description: "SceneDiary는 사용자가 업로드한 여행 사진을 AI가 해석하고, 선택한 페르소나의 문체로 그 순간을 일기처럼 풀어내는 팀 프로젝트입니다.",
  },
  {
    id: 5,
    title: "🔧 Fixie — 복잡한 가전 매뉴얼을 AI로 재구조화하는 서비스",
    category: "Team Project",
    status: "Done",
    snapshot: "https://hqefyvwzlhytnmhqbggt.supabase.co/storage/v1/object/public/images/uploads/1778142181960_5efe036a-769c-4a0b-bd32-778c9cba0190.png",
    description: "QR 코드나 모델명으로 기기를 등록하고, 매뉴얼을 학습한 AI와 대화하며 해결 방법을 찾는 팀 프로젝트입니다.",
  },
  {
    id: 4,
    title: "🔮 Y-Insight Engine— 모든 앱을 연결하는 공통의 뇌",
    category: "AI Projects",
    status: "In Progress",
    snapshot: "https://hqefyvwzlhytnmhqbggt.supabase.co/storage/v1/object/public/images/uploads/1778141843010_8e7a80de-dd23-462d-a5cc-2853a8eadb92.png",
    description: "여러 앱이 함께 쓸 수 있는 공통 AI 백엔드와 도메인별 GraphRAG 구조를 설계한 프로젝트입니다.",
  },
  {
    id: 3,
    title: "🌙 Mood-DNA — 디자이너의 감각을 논리로 증명하는 AI",
    category: "AI Projects",
    status: "In Progress",
    snapshot: "https://hqefyvwzlhytnmhqbggt.supabase.co/storage/v1/object/public/images/uploads/1778141883119_e2320671-2664-48cd-acf4-abdd0aa16b5d.png",
    description: "OpenCV와 AI 비평을 결합해 디자인의 시각적 지표와 무드를 분석하는 디자인 파트너입니다.",
  },
  {
    id: 2,
    title: "☕ Cof/fee — 커피를 안전하게 즐기기 위한 카페인 관리 앱",
    category: "AI Projects",
    status: "In Progress",
    snapshot: "https://hqefyvwzlhytnmhqbggt.supabase.co/storage/v1/object/public/images/uploads/1778140113100_d9f75ee8-3967-4ba2-ba8a-1f3b4100a994.png",
    description: "개인화된 카페인 반감기 계산과 수면 신호를 통해 커피 섭취를 조절하는 건강 관리 앱입니다.",
  },
  {
    id: 1,
    title: "🍓 Focus Mate Berry — 나의 공부 친구",
    category: "AI Projects",
    status: "In Progress",
    snapshot: "https://hqefyvwzlhytnmhqbggt.supabase.co/storage/v1/object/public/images/uploads/1778119134337_berry.png",
    description: "MediaPipe와 OpenCV로 공부 자세를 감지하고 캐릭터 상태 변화로 집중을 돕는 AI 공부 친구입니다.",
  },
  {
    id: 9,
    title: "📛 당신의 이름은 어떤 시대인가요? — 130년의 기록",
    category: "Data Visualization",
    status: "Done",
    snapshot: "https://hqefyvwzlhytnmhqbggt.supabase.co/storage/v1/object/public/images/uploads/1778240287323_08555f9c-269e-4366-aabd-acd88f04de4b.png",
    description: "1880년부터 2010년까지 미국 신생아 이름 데이터를 바탕으로 사회 변화와 이름의 흐름을 시각화했습니다.",
  },
  {
    id: 8,
    title: "🏛️ 땅에서 박물관까지 — 유물은 어디서 와서 어디로 가는가",
    category: "Data Visualization",
    status: "Done",
    snapshot: "https://hqefyvwzlhytnmhqbggt.supabase.co/storage/v1/object/public/images/uploads/1778240284023_f1510614-5e40-47b9-9260-6c796a3599d7.png",
    description: "문화유산 데이터를 정제하고 유물이 발견지에서 박물관으로 이동하는 흐름을 Tableau로 시각화했습니다.",
  },
  {
    id: 7,
    title: "🎡 대한민국 사람들의 문화생활 엿보기",
    category: "Data Visualization",
    status: "Done",
    snapshot: "https://hqefyvwzlhytnmhqbggt.supabase.co/storage/v1/object/public/images/uploads/1778240280610_20c8a7e8-b9b7-4b0a-b056-b9de83c635dc.png",
    description: "국민여가활동조사 데이터를 시간, 지역, 연령 관점으로 나누어 문화생활의 차이를 시각화했습니다.",
  },
  {
    id: 6,
    title: "🛣️ 고속도로 휴게소는 왜 사람이 많을까?",
    category: "Data Visualization",
    status: "Done",
    snapshot: "https://hqefyvwzlhytnmhqbggt.supabase.co/storage/v1/object/public/images/uploads/1778240272345_df903481-6d03-48a9-840b-37823e409ebc.png",
    description: "교통량, 이용객, 체류 환경, 매출 지표를 분리해 휴게소 이용 패턴을 탐색한 시각화 프로젝트입니다.",
  },
];
